# config.yml
trivy:
  enabled: true
  timeout: 90        # seconds
  block_if_high_or_critical: 1   # number of HIGH+CRITICAL to block
  cache_ttl_minutes: 60

gate:
  mode: "enforce"    # "enforce" blocks; "monitor" only logs
  auto_remove_blocked_container: true

falco:
  auto_stop_on_rules:
    - "Write below etc"
    - "Read sensitive file"
    - "Read sensitive file untrusted"
    - "Suspicious Download Tool In Container"
    - "Outbound connection from container"
    - "Package manager activity in container"
    - "Ptrace syscall used"
    - "Root running unknown binary"
    - "Outbound connection from container (refined)"
    - "Read sensitive SSH file in container"
    # - Drop and execute new binary in container
  stop_grace_seconds: 2
